#### general settings
name: realSR_x3_model_RCAN
use_tb_logger: true
model: sr
distortion: sr
scale: 3
gpu_ids: [0,1]

MixCorrupt: True

#### datasets
dataset:
  test:
    name: Validation_Test_x3
    mode: LR
    dataroot_LR: /disk/whn/AIM2020_real_SR/ValidationLR_x3
datasets:
  train:
    name: DF2K_train 
    mode: LQGT    
    dataroot_GT: /disk/whn/AIM2020_real_SR/Train/HR
    dataroot_LQ: /disk/whn/AIM2020_real_SR/Train/LR

    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 32
    GT_size: 192
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K_val
    mode: LQGT
    GT_size: 384
    dataroot_GT: /disk/whn/AIM2020_real_SR/Valid/HR
    dataroot_LQ: /disk/whn/AIM2020_real_SR/Valid/LR
    
#### network structures
network_G:
  in_nc: 3
  out_nc: 3
  which_model_G: RCAN
  n_resgroups: 8
  n_resblocks: 8
  nf: 64
  kernel_size: 3
  reduction: 16
  scale: 3

#### path
path:
  dsgan_model: 
  pretrain_model_G: #../experiments/realSR_x3_model_RCAN/models/3457_G.pth #only for testing
  strict_load: true
  resume_state: # ../experiments/DF2K_jpeg_SDSR_model/training_state/45000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 5e-5
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  lr_scheme: MultiStepLR

  niter: 51000
  warmup_iter: -1  # no warm up
  lr_steps: [5000, 10000, 20000, 30000]
  lr_gamma: 0.5

  use_filters: True
  pixel_criterion: l2
  pixel_weight: !!float 1
  dual_weight: !!float 1e-3
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 1

#### logger
logger:
  tb_freq: 10
  print_freq: 1
  save_checkpoint_freq: 3
