#### general settings
name: DF2K_jpeg_SDSR
use_tb_logger: true
model: sr
distortion: sr
scale: 4
Crop: false
gpu_ids: [0,1]

#### datasets
datasets:
  train:
    name: DF2K_train 
    mode: LQGT    
    dataroot_GT: /home/whn/RCAN/X4/Train/HR
    dataroot_LQ: /home/whn/RCAN/X4/Train/LR

    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DIV2K_val
    mode: LQGT
    GT_size: 1024
    dataroot_GT: /home/whn/RCAN/X4/Valid/HR
    dataroot_LQ: /home/whn/RCAN/X4/Valid/LR
    
#### network structures
network_DS:
  gene:
    n_blocks: 4
    n_groups: 2
    scale: 1
    need_ca: False
    need_dense: False
    red: 16
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23


#### path
path:
  dsgan_model: 
  pretrain_model_G: 
  strict_load: true
  resume_state: # ../experiments/DF2K_jpeg_SDSR_model/training_state/45000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 51000
  warmup_iter: -1  # no warm up
  lr_steps: [5000, 10000, 20000, 30000]
  lr_gamma: 0.5

  use_filters: True
  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 5

#### logger
logger:
  tb_freq: 10
  print_freq: 1
  save_checkpoint_freq: 5
