#### general settings
name: DPED_TDSR_DRDM
use_tb_logger: true
model: cosrgan
distortion: sr
scale: 4
medium: true
gpu_ids: [0,1]

need_reverse: false
baseline: false

#### datasets
dataset:
  test:
    name: DPED_test
    mode: LR
    dataroot_LR: ../../datasets/DPEDiphone-crop-te-x
datasets:
  train:
    target: false
    name: DPED_train 
    mode: LQGT    
    dataroot_GT: ../../datasets/DPED/generated/avarice/train_tdsr/HR
    dataroot_LQ: ../../datasets/DPED/generated/avarice/train_tdsr/LR

    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: DPED_test
    mode: LQGT
    GT_size: 1024
    dataroot_GT: ../../datasets/DPED/generated/avarice/val_tdsr/HR
    dataroot_LQ: ../../datasets/DPED/generated/avarice/val_tdsr/LR
    
#### network structures
network_DS:
  path: ../../w
  disc:
    recursions: 1
    stride: 1 
    kernel_size: 5
  gene:
    n_blocks: 4
    n_groups: 2
    scale: 1
    need_ca: false
    need_dense: false
    red: 16
network_G:
  which_model_G: MSRResNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 12
  nu: 3
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

#### path
path:
  pretrain_model_NG: /home/whn/real-world-sr/esrgan-fs/experiments/DPED_SDSR_NTIRE/models/2441_NG.pth
  pretrain_model_ND: /home/whn/real-world-sr/esrgan-fs/experiments/DPED_SDSR_NTIRE/models/2441_ND.pth
  pretrain_model_G: #/home/whn/real-world-sr/esrgan-fs/experiments/DPED_SDSR/models/1832_G.pth
  pretrain_model_D: #/home/whn/real-world-sr/esrgan-fs/experiments/DPED_SDSR/models/1832_D.pth
  strict_load: true
  resume_state: 

#### training settings: learning rate scheme, loss, co-training
train:
  DRDM: true
  need_reverse: true
  reverse_weight: !!float 1
  lr_ND: !!float 1e-4
  lr_NG: !!float 1e-4
  beta_1: 0.9
  beta_2: 0.999

  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 51000
  warmup_iter: -1  # no warm up
  lr_steps: [5000, 10000, 20000, 30000]
  lr_gamma: 0.5

  use_filters: true
  dual_criterion: l1
  dual_weight: !!float 1
  pixel_criterion: l1
  pixel_weight: !!float 20
  feature_criterion: l2
  feature_weight: !!float 2e-1
  lpips_weight: !!float 1e-3
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-1
  ref_weight: !!float 2e-1


  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: 5

#### logger
logger:
  tb_freq: 10
  print_freq: 1
  save_checkpoint_freq: 5
